# Generated by Django 5.2.5 on 2025-08-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prioritt',
            new_name='priority',
        ),
    ]
