# Generated by Django 5.2.5 on 2025-08-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_prioritt_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Media'), ('Alta', 'Alta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Atendimento', 'Progresso'), ('Resolvido', 'Resolvido'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
